import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";

import UserHome from "~/scenes/UserHome";
import Home from "~/scenes/Home";

const Index: NextPage = () => {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Mindfully</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon-16x16.png" />
      </Head>

      {sessionData ? <UserHome /> : <Home />}
    </>
  );
};

export default Index;
